spring:
  datasource:
    url : jdbc:mysql://localhost:3306/mylog
    username : root
    password : Init1234
    driverClassName : com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql